# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: flask


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080